# Generated by Django 5.1.7 on 2025-03-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_product_alter_tag_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
    ]
