# Generated by Django 5.1.7 on 2025-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_taggroup_tag_tag_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
