# Generated by Django 5.1.7 on 2025-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_tag_value_alter_taggroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
