# Generated by Django 5.1.7 on 2025-08-06 16:33
from django.db import models
from django.db import migrations
from django.utils.text import slugify

def populate_tag_slugs(apps, schema_editor):
    Tag = apps.get_model('category', 'Tag')
    TagGroup = apps.get_model('category', 'TagGroup')

    for tag in Tag.objects.all():
        group = TagGroup.objects.get(id=tag.tag_group_id)
        raw_slug = f"{group.name}_{tag.name}"
        tag.slug = slugify(raw_slug)
        tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_taggroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=120, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(populate_tag_slugs),
    ]
