# Generated by Django 5.1.7 on 2025-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_tag_value_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
