# Generated by Django 5.1.7 on 2025-07-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.JSONField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
