# Generated by Django 5.1.7 on 2025-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productjson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductJSON',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(),
        ),
    ]
