# Generated by Django 5.1.7 on 2025-08-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_created_at_productimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='details',
        ),
    ]
