# Generated by Django 5.1.7 on 2025-08-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_description_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='description',
        ),
    ]
