# Generated by Django 5.1.7 on 2025-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_product_img_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
