# Generated by Django 5.1.7 on 2025-10-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_img',
        ),
    ]
