# Generated by Django 5.1.7 on 2025-10-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
