# Generated by Django 5.1.7 on 2025-10-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vendorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pfp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vpfp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
